config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources  :users do
   resources :postings, only: [:index, :edit, :update]
  end
  
  root "home#index"
  
  resources :postings, only: [:create, :show, :new, :update] do
    get '/renew', to: "postings#renew"
  end
  
  resources :transactions, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/posting.rb
class Posting < ActiveRecord::Base
  mount_uploader :logo, LogoUploader
  
  POSTING_FEE = 150
  RENEWAL_FEE = 50
  
  validates_presence_of :user_id, :description, :job_title, :kind, :company_name,
                         :company_location, :application_instructions
  
  belongs_to :user
  has_many :transactions
  
  enum kind: { programming: 0, marketing: 1, design: 2, devops: 3, customer_support: 4}
  
  after_create :queue_exipration_job
  after_create :queue_reminder_job
  
  scope :active, -> { where(expired: false) }
  
  def renew
    self.update_attribute(:expires_at, self.expires_at + 30.days) 
  end
  
  def new?
    self.created_at >= 5.days.ago.beginning_of_day
  end
  
  private
  
  def queue_exipration_job
    CheckExpiredPostingsJob.set(wait: 30.days).perform_later(self)
  end
  
  def queue_reminder_job
    ExpirationReminderJob.set(wait: 25.days).perform_later(self)
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  validates_presence_of :user_id, :posting_id, :transaction_id, :status, :amount
  
  belongs_to :user
  belongs_to :posting
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :postings
  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  helper_method :resource_name, :resource, :devise_mapping
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end  

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end  
end

app/controllers/concerns/postings_concern.rb
module PostingsConcern

  def self.grouped_postings
    hash = {}
    Posting.kinds.keys.each do |kind|
      hash[kind] = Posting.active.where(kind: kind).order(created_at: :desc)
    end
    
    hash
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @postings = ::PostingsConcern.grouped_postings
  end
  
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  
  def index
    if params[:user_id] && (current_user && current_user.id == params[:user_id].to_i)
      @user = current_user
      @postings = @user.postings
    else
      redirect_to root_url
    end
  end
  
  def edit
    @posting = Posting.find(params[:id])
    
    authorize(@posting)
    
    render :edit
  end
  
  def update
    @posting = Posting.find(params[:id])

    authorize(@posting)
    
    if @posting.update(posting_params)
      redirect_to posting_path(@posting)
    else
      render :edit
    end
  end
  
  def create
    @posting = Posting.new(posting_params)

    authorize(@posting)

    if (params[:commit] == 'Preview') || (params[:commit] == "Edit")
      render :new
    elsif @posting.save
      @amount = Posting::POSTING_FEE
      render :new
    else
      render :new
    end
  end
  
  def show
    @posting = Posting.find(params[:id])
  end
  
  def new
    @posting = Posting.new
    @amount = Posting::POSTING_FEE

    authorize(@posting)
  end
  
  def renew
    @posting = Posting.find(params[:posting_id])
    @renewal = true
    @amount = Posting::RENEWAL_FEE
  end
  
  private
  
  def posting_params
    params.require(:posting).permit(:user_id, :description, :job_title, :kind, :company_name, :company_location,
                                    :application_instructions, :logo)
  end
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
  def create    
    @charge = JobBoard::Stripe::CreateCharge.new({token: params[:stripeToken], 
                                                 email: current_user.email,
                                                 posting_id: params[:posting_id],
                                                 amount: params[:amount].to_i}).execute

    transaction = Transaction.new(transaction_params)
    authorize(transaction)
    
    if transaction.save
      posting = Posting.find(params[:posting_id])

      if params[:renewal]
        posting.expires_at = (posting.expires_at + 30.days)
      end
      
      posting.expired = false
      posting.save
      
      redirect_to posting_path(posting) 
    else
      render :new
    end
  end
  
  private
  
  def transaction_params
    { posting_id: params[:posting_id], user_id: current_user.id, transaction_id: @charge.id, status: @charge.status, amount: @charge.amount }
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # adds new-posting class to new postings
  def new_posting?(posting)
    if posting.new?
      html = "<span class='badge'>NEW!</span>"
      html.html_safe
    end
  end
  
end

app/views/home/index.html.haml
.container
  %h1 Job Board
  %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia pharetra erat in pellentesque. In sagittis ultrices malesuada. 
  .panel.panel-primary
    .panel-body
      - @postings.each do |pg|
        %h3
          = pg[0].capitalize
        .panel.panel-default
          %table.table.table-striped
            %tbody
              - pg[1].each do |p|
                %tr
                  %td
                    %b
                      = "#{p.company_name}"
                    &nbsp;
                    = link_to p.job_title, posting_path(p)
                    &nbsp;
                    = new_posting?(p)
                    .pull-right
                      = p.created_at.strftime("%b, %e")

app/views/layouts/_devise_links.html.haml
- unless current_user
  .row
    %button.btn.btn-primary.btn-lg{"data-target" => "#signUpModal", "data-toggle" => "modal", :type => "button"}
      Sign Up
    #signUpModal.modal.fade{"aria-labelledby" => "signUpModal", :role => "dialog", :tabindex => "-1"}
      .modal-dialog{:role => "document"}
        .modal-content
          .modal-header
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
          .modal-body
            = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
              = devise_error_messages!
              .field
                = f.label :email
                %br/
                = f.email_field :email, autofocus: true
              .field
                = f.label :password
                - if @minimum_password_length
                  %em
                    (#{@minimum_password_length} characters minimum)
                %br/
                = f.password_field :password, autocomplete: "off"
              .field
                = f.label :password_confirmation
                %br/
                = f.password_field :password_confirmation, autocomplete: "off"
              .actions
                = f.submit "Sign up", class: "btn btn-primary"
            = render "devise/shared/links"
            
    %button.btn.btn-primary.btn-lg{"data-target" => "#signInModal", "data-toggle" => "modal", :type => "button"}
      Sign In
    #signInModal.modal.fade{"aria-labelledby" => "signInModal", :role => "dialog", :tabindex => "-1"}
      .modal-dialog{:role => "document"}
        .modal-content
          .modal-header
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
          .modal-body
            %h2 Log in
            = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
              .field
                = f.label :email
                %br/
                = f.email_field :email, autofocus: true
              .field
                = f.label :password
                %br/
                = f.password_field :password, autocomplete: "off"
              - if devise_mapping.rememberable?
                .field
                  = f.check_box :remember_me
                  = f.label :remember_me
              .actions
                = f.submit "Log in"
            = render "devise/shared/links"
- else
  = link_to('Logout', destroy_user_session_path, :method => :delete)

app/views/layouts/_nav_links.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_url} Job Board
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
      %ul.nav.navbar-nav.navbar-right
        - unless current_user
          %li
            = link_to "Create Listing", "#", "data-toggle" => "modal", "data-target" => "#signUpModal"  
          %li
            = link_to "Sign In", "#", "data-toggle" => "modal", "data-target" => "#signInModal"              
        - else
          %li
            = link_to 'My Postings', user_postings_path(current_user)
          %li
            = link_to "New Posting", new_posting_path
          %li
            = link_to('Logout', destroy_user_session_path, :method => :delete)        
          
#signUpModal.modal.fade{"aria-labelledby" => "signUpModal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
          = devise_error_messages!
          .field
            = f.label :email
            %br/
            = f.email_field :email, autofocus: true
          .field
            = f.label :password
            - if @minimum_password_length
              %em
                (#{@minimum_password_length} characters minimum)
            %br/
            = f.password_field :password, autocomplete: "off"
          .field
            = f.label :password_confirmation
            %br/
            = f.password_field :password_confirmation, autocomplete: "off"
          .actions
            = f.submit "Sign up", class: "btn btn-primary"
        = render "devise/shared/links"          

#signInModal.modal.fade{"aria-labelledby" => "signInModal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        %h2 Log in
        = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
          .field
            = f.label :email
            %br/
            = f.email_field :email, autofocus: true
          .field
            = f.label :password
            %br/
            = f.password_field :password, autocomplete: "off"
          - if devise_mapping.rememberable?
            .field
              = f.check_box :remember_me
              = f.label :remember_me
          .actions
            = f.submit "Log in"
        = render "devise/shared/links"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JobBoard
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render 'layouts/nav_links'
    = yield

app/views/postings/_errors.html.haml
- if @posting.errors.any?
  %h3 Please fix these errors:
  %ul
    - @posting.errors.full_messages.each do |message|
      %li= message

app/views/postings/_form.html.haml
= render 'errors'

= form_for @posting do |f|
  = f.hidden_field :user_id, value: current_user.id
  .form-group
    = f.label :job_title
    %br
    = f.text_field :job_title, autofocus: true, requried: true
  .form-group
    = f.label :kind
    %br
    = f.select(:kind, options_for_select(Posting.kinds.keys)) 
  .form-group
    = f.label :description
    %br
    = f.text_area :description, requried: true, class: 'froala-editor'
  .form-group
    = f.label :company_name
    %br
    = f.text_field :company_name, requried: true
  .form-group
    = f.label :company_location
    %br
    = f.text_field :company_location, requried: true
  .form-group
    = f.label :logo
    %br
    = f.file_field :logo
  .form-group
    = f.label :application_instructions
    %br
    = f.text_area :application_instructions, requried: true, class: 'froala-editor'
  %br
  - if @posting.persisted?
    = f.submit 'Update'
  - else
    = f.submit "Create Posting"  
    = f.submit "Preview"   

app/views/postings/_preview.html.haml
.container
  %hr
  .row
    .col-md-8
      %h2
        = @posting.job_title
      = "Posted #{Time.now.strftime("%b %e")}"
      %br
      %br
      %h4
        %b
          = @posting.company_name
        %br
        = "Location: #{@posting.company_location}"
        %br
          = link_to @posting.company_url, @posting.company_url
    .col-md-4
      .company-logo-img
        = image_tag "https://placeholdit.imgix.net/~text?txtsize=33&txt=150%C3%97150&w=150&h=150"
  %hr
  .row 
    .col-md-8
      = @posting.description.html_safe    
    .col-md-4
  %hr
  .well
    %h4
      %b How to Apply:
    = @posting.application_instructions.html_safe

= form_for @posting do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :job_title, value: @posting.job_title
  = f.hidden_field :company_name, value: @posting.company_name
  = f.hidden_field :company_location, value: @posting.company_location
  = f.hidden_field :kind, value: @posting.kind
  = f.hidden_field :description, value: @posting.description
  = f.hidden_field :application_instructions, value: @posting.application_instructions
  = f.submit "Edit" 
  = f.submit "Create Posting"  

app/views/postings/edit.html.haml
.container
  = render 'form'

app/views/postings/index.html.haml
.container
  %table.table.table-bordered
    %tbody
      - @postings.each do |p|
        %tr
          %td
            %b
              = p.company_name
            &nbsp;
            = link_to p.job_title, posting_path(p)
            &nbsp;
            = link_to "Edit", "/users/#{current_user.id}/postings/#{p.id}/edit"
            .pull-right
              = p.created_at.strftime("%a %e")

app/views/postings/new.html.haml
.container  
  - if params[:commit] == "Preview"
    = render 'preview'
  - elsif @posting.persisted?
    %h2 Post this listing for 30 days for $150
    = render 'transactions/payment_form'
  - else
    = render 'form'

app/views/postings/renew.html.haml
.container
  %h2 Renew now for $50
  = render 'transactions/payment_form'

app/views/postings/show.html.haml
.container
  %hr
  .row
    .col-md-8
      %h2
        = @posting.job_title
      = "Posted #{@posting.created_at.strftime("%b %e")}"
      %br
      %br
      %h4
        %b
          = @posting.company_name
        %br
        = "Location: #{@posting.company_location}"
        %br
          = link_to @posting.company_url, @posting.company_url
    .col-md-4
      .company-logo-img
        = image_tag @posting.logo.thumb
  %hr
  .row 
    .col-md-8
      = @posting.description.html_safe    
    .col-md-4
  %hr
  .well
    %h4
      %b How to Apply:
    = @posting.application_instructions.html_safe

app/views/transactions/_payment_form.html.haml
= javascript_include_tag "https://js.stripe.com/v2/"
:javascript
  Stripe.setPublishableKey('pk_test_YStIP55lyAkrdDbhp1fUUCl3');

= form_tag transactions_path, method: 'post', id: 'payment-form' do   
  %span.payment-errors
  
  = hidden_field_tag :posting_id, @posting.id
  = hidden_field_tag :amount, @amount
  = hidden_field_tag :renewal, @renewal

  = label_tag "Card Number", nil, required: true
  .control-group
    .controls
      = text_field_tag :card_number, nil, class: "input-block-level", "data-stripe" => "number"

  = label_tag "Card Verification", nil, required: true
  .control-group
    .controls
      = text_field_tag :card_verification, nil, class: "input-block-level", "data-stripe" => "cvv"

  = label_tag "Card Expires", nil, required: true
  = select_tag :exp_month, options_for_select(Date::MONTHNAMES.compact.each_with_index.map { |name,i| ["#{i+1} - #{name}", i+1] }), include_blank: false, "data-stripe" => "exp-month", class: "span2"
  = select_tag :exp_year, options_for_select((Date.today.year..(Date.today.year+10)).to_a), include_blank: false, "data-stripe" => "exp-year", class: "span1"

  .actions
    = submit_tag "Submit Payment", class: "btn", style: "color: white;background: rgb(242, 118, 73);"